---
title: "Data manipulation"
output: github_document
---

```{r, setup}
library(tidyverse)
```

##Load in the FAS Litters Data

```{r}
litters_df = read_csv("./data/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)

pups_df = read_csv("data/FAS_pups.csv")
pups_df = janitor::clean_names(pups_df)
```

###learning assessment
```{r}
select(pups_df, litter_number, sex, pd_ears)
```

```{r}
pull(litters_df, group)
```

## `select`

Choose some columns and not others.

```{r}
select(litters_df, group, litter_number)#tell select what column I want to keep__only keep the 'litter_number' column
select(litters_df, group, gd0_weight,gd18_weight)

select(litters_df, -litter_number)
```

```{r}
select(litters_df, group, gd0_weight:gd_of_birth)#save the columns from `gd0_weight` to `gd_of_birth`
```

```{r}
select(litters_df, -litter_number)#keep everything else except `litter_number` column
```

Renaming columns...

```{r}
select(litters_df, GROUP = group, LITTer_NUmBer = litter_number)#pick out the columns and change the name of the column
```

```{r}
rename(litters_df, GROUP = group, LITTer_NUmBer = litter_number)#save all the columns and rename one or several of them
```

Select helpers

```{r}
select(litters_df, starts_with("gd"))#select all the columns whose name starts with gd
select(litters_df, starts_with("pups"))
```

```{r}
select(litters_df, litter_number, everything()) #a way to relocate, put"litter_number" to the 1st column
```

```{r}
relocate(litters_df, litter_number)#put `litter_number` to the 1st column
```

##`filter`
###remove rows and keep rows


```{r}
filter(litters_df, gd0_weight < 22)#only save the gd0_weight data which is less than 22
```

```{r}
filter(litters_df, gd_of_birth == 20)#==is a test, whether they are equal or not, save the datas whivh birth is exactly equal to 20
filter(litters_df, group == "Con7")
```

```{r}
filter(litters_df, !(gd_of_birth == 20))#give all the datas that birth is not equal to 20
```

```{r}
filter(litters_df, group == "Con7")
```

```{r}
filter(litters_df, group %in% c("con7","Mod8"))
```

```{r}
filter(litters_df, pups_survive != 4)#######???????????

filter(litters_df, group %in% c("Con7","Con8"))#only interested in con7 and con8

filter(litters_df, group == "Con7" | group == "Con8")

drop_na(litters_df)
drop_na(litters_df, gd_of_birth)##delete na
```


## `mutate`

```{r}
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower("group")##make the group lower
  )
```


##`arrange`


```{r}
arrange(litters_df,pups_born_alive)#arrange based on pups_born_alive order(small number to large number)
```

## `%>%`

```{r}
litters_data_raw = read_csv("./data/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_data_selected = select(litters_clean_name, -pups_survive)
litters_mutated = mutate(litters_data_selected, wt_gain = gd18_weight - gd0_weight)
litters_without_missing = drop_na(litters_mutated, gd0_weight)
```

Use the PIPE OPERATOR instead(more brief)

```{r}
litters_df = (
  read_csv("./data/FAS_litters.csv") %>% #shift+ctrl+m----%>%---don't need to repeat anything
    janitor::clean_names() %>%
    select(-pups_survive) %>% 
    drop_na(gd0_weight)
)
```


```{r}
litters_df = 
  read_csv("./data/FAS_litters.csv") %>% #shift+ctrl+m----%>%---don't need to repeat anything
    janitor::clean_names() %>%
    select(-pups_survive) %>% 
mutate(
  litters_df, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower("group")##make the group lower
  ) %>%
  drop_na(weight_change)
```




